### ISSUE TITLE
Update to RxJS 5.5.5?

### ISSUE THREAD

**Issue by Zolomon** [iansinnott/rxjs-dash-docset#2]
Would it be possible to update this docset to the latest version of RxJS, 5.5.5 as of writing?

**Comment by iansinnott** [comment]
Yeah, thanks for the heads up. I had actually been not bothering to update the docs because as far as I can tell the docs haven't actually been updated. For example, there's no mention (that I could find) of [lettable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md) in the docs.

So, I'd be happy to update the docset, but have the docs actually changed?

**Comment by Zolomon** [comment]
No, you are correct! I apologise, I just assumed that the docset was out of sync with the documentation for RxJS. It surely does not look like there is any documentation for lettable operators (which was what I was looking for) other than what you just linked. 

Let's close this?

**Comment by iansinnott** [comment]
No problem! Yeah the rxjs docs seem to lag behind development quite a bit. I seem to remember being unable to find any docs for certain operators in the past... although I can't remember off-hand what they were. 

Anyway, yeah I'll close this out.
